[build]
builder = "DOCKERFILE"
dockerfilePath = "ahorro365-baileys-worker/Dockerfile"

[deploy]
workingDirectory = "ahorro365-baileys-worker"
startCommand = "node dist/index.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

