// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/delete-data" | "/privacy" | "/terms"
type AppRouteHandlerRoutes = "/api/admin/app-versions" | "/api/admin/app-versions/stats" | "/api/ai" | "/api/app/version-check" | "/api/audio/process" | "/api/cron/confirm-expired" | "/api/csrf-token" | "/api/debug/trace-transaction" | "/api/dev/reset-daily-transactions" | "/api/feedback/confirm" | "/api/feedback/stats" | "/api/migrations/add-smart-fecha-inicio-programada" | "/api/notifications/campaigns" | "/api/notifications/campaigns/[id]" | "/api/notifications/campaigns/[id]/execute" | "/api/notifications/campaigns/run" | "/api/notifications/debug/create-log" | "/api/notifications/events" | "/api/notifications/logs" | "/api/notifications/logs/summary" | "/api/notifications/logs/trend" | "/api/notifications/monitoring" | "/api/notifications/preferences" | "/api/notifications/register-token" | "/api/notifications/send" | "/api/notifications/templates" | "/api/notifications/templates/[id]" | "/api/notifications/triggers" | "/api/notifications/triggers/[key]" | "/api/notifications/triggers/[key]/run" | "/api/notifications/triggers/referral-invited" | "/api/notifications/triggers/referral-verified" | "/api/payments/create" | "/api/payments/upload-receipt" | "/api/ping" | "/api/process-expense" | "/api/referrals/activate-smart" | "/api/referrals/validate-code" | "/api/test/smart-activation" | "/api/webhooks/baileys" | "/api/webhooks/whatsapp" | "/api/webhooks/whatsapp/confirm" | "/api/webhooks/whatsapp/debug" | "/api/whatsapp/events" | "/api/whatsapp/health" | "/api/whatsapp/metrics" | "/api/whatsapp/send-verification-code" | "/api/whatsapp/status" | "/api/whatsapp/test-token" | "/api/whatsapp/verify-code"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/admin/app-versions": {}
  "/api/admin/app-versions/stats": {}
  "/api/ai": {}
  "/api/app/version-check": {}
  "/api/audio/process": {}
  "/api/cron/confirm-expired": {}
  "/api/csrf-token": {}
  "/api/debug/trace-transaction": {}
  "/api/dev/reset-daily-transactions": {}
  "/api/feedback/confirm": {}
  "/api/feedback/stats": {}
  "/api/migrations/add-smart-fecha-inicio-programada": {}
  "/api/notifications/campaigns": {}
  "/api/notifications/campaigns/[id]": { "id": string; }
  "/api/notifications/campaigns/[id]/execute": { "id": string; }
  "/api/notifications/campaigns/run": {}
  "/api/notifications/debug/create-log": {}
  "/api/notifications/events": {}
  "/api/notifications/logs": {}
  "/api/notifications/logs/summary": {}
  "/api/notifications/logs/trend": {}
  "/api/notifications/monitoring": {}
  "/api/notifications/preferences": {}
  "/api/notifications/register-token": {}
  "/api/notifications/send": {}
  "/api/notifications/templates": {}
  "/api/notifications/templates/[id]": { "id": string; }
  "/api/notifications/triggers": {}
  "/api/notifications/triggers/[key]": { "key": string; }
  "/api/notifications/triggers/[key]/run": { "key": string; }
  "/api/notifications/triggers/referral-invited": {}
  "/api/notifications/triggers/referral-verified": {}
  "/api/payments/create": {}
  "/api/payments/upload-receipt": {}
  "/api/ping": {}
  "/api/process-expense": {}
  "/api/referrals/activate-smart": {}
  "/api/referrals/validate-code": {}
  "/api/test/smart-activation": {}
  "/api/webhooks/baileys": {}
  "/api/webhooks/whatsapp": {}
  "/api/webhooks/whatsapp/confirm": {}
  "/api/webhooks/whatsapp/debug": {}
  "/api/whatsapp/events": {}
  "/api/whatsapp/health": {}
  "/api/whatsapp/metrics": {}
  "/api/whatsapp/send-verification-code": {}
  "/api/whatsapp/status": {}
  "/api/whatsapp/test-token": {}
  "/api/whatsapp/verify-code": {}
  "/delete-data": {}
  "/privacy": {}
  "/terms": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
