// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/delete-data/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/delete-data">> = Specific
  const handler = {} as typeof import("../../src/app/delete-data/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/privacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privacy">> = Specific
  const handler = {} as typeof import("../../src/app/privacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/terms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/terms">> = Specific
  const handler = {} as typeof import("../../src/app/terms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/app-versions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/app-versions">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/app-versions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/app-versions/stats/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/app-versions/stats">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/app-versions/stats/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ai/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai">> = Specific
  const handler = {} as typeof import("../../src/app/api/ai/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/app/version-check/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/app/version-check">> = Specific
  const handler = {} as typeof import("../../src/app/api/app/version-check/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/audio/process/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/audio/process">> = Specific
  const handler = {} as typeof import("../../src/app/api/audio/process/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cron/confirm-expired/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/confirm-expired">> = Specific
  const handler = {} as typeof import("../../src/app/api/cron/confirm-expired/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/csrf-token/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/csrf-token">> = Specific
  const handler = {} as typeof import("../../src/app/api/csrf-token/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/debug/trace-transaction/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/debug/trace-transaction">> = Specific
  const handler = {} as typeof import("../../src/app/api/debug/trace-transaction/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/dev/reset-daily-transactions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dev/reset-daily-transactions">> = Specific
  const handler = {} as typeof import("../../src/app/api/dev/reset-daily-transactions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/feedback/confirm/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/feedback/confirm">> = Specific
  const handler = {} as typeof import("../../src/app/api/feedback/confirm/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/feedback/stats/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/feedback/stats">> = Specific
  const handler = {} as typeof import("../../src/app/api/feedback/stats/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/migrations/add-smart-fecha-inicio-programada/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/migrations/add-smart-fecha-inicio-programada">> = Specific
  const handler = {} as typeof import("../../src/app/api/migrations/add-smart-fecha-inicio-programada/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/notifications/campaigns/[id]/execute/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notifications/campaigns/[id]/execute">> = Specific
  const handler = {} as typeof import("../../src/app/api/notifications/campaigns/[id]/execute/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/notifications/campaigns/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notifications/campaigns/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/notifications/campaigns/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/notifications/campaigns/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notifications/campaigns">> = Specific
  const handler = {} as typeof import("../../src/app/api/notifications/campaigns/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/notifications/campaigns/run/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notifications/campaigns/run">> = Specific
  const handler = {} as typeof import("../../src/app/api/notifications/campaigns/run/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/notifications/debug/create-log/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notifications/debug/create-log">> = Specific
  const handler = {} as typeof import("../../src/app/api/notifications/debug/create-log/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/notifications/events/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notifications/events">> = Specific
  const handler = {} as typeof import("../../src/app/api/notifications/events/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/notifications/logs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notifications/logs">> = Specific
  const handler = {} as typeof import("../../src/app/api/notifications/logs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/notifications/logs/summary/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notifications/logs/summary">> = Specific
  const handler = {} as typeof import("../../src/app/api/notifications/logs/summary/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/notifications/logs/trend/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notifications/logs/trend">> = Specific
  const handler = {} as typeof import("../../src/app/api/notifications/logs/trend/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/notifications/monitoring/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notifications/monitoring">> = Specific
  const handler = {} as typeof import("../../src/app/api/notifications/monitoring/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/notifications/preferences/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notifications/preferences">> = Specific
  const handler = {} as typeof import("../../src/app/api/notifications/preferences/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/notifications/register-token/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notifications/register-token">> = Specific
  const handler = {} as typeof import("../../src/app/api/notifications/register-token/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/notifications/send/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notifications/send">> = Specific
  const handler = {} as typeof import("../../src/app/api/notifications/send/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/notifications/templates/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notifications/templates/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/notifications/templates/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/notifications/templates/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notifications/templates">> = Specific
  const handler = {} as typeof import("../../src/app/api/notifications/templates/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/notifications/triggers/[key]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notifications/triggers/[key]">> = Specific
  const handler = {} as typeof import("../../src/app/api/notifications/triggers/[key]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/notifications/triggers/[key]/run/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notifications/triggers/[key]/run">> = Specific
  const handler = {} as typeof import("../../src/app/api/notifications/triggers/[key]/run/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/notifications/triggers/referral-invited/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notifications/triggers/referral-invited">> = Specific
  const handler = {} as typeof import("../../src/app/api/notifications/triggers/referral-invited/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/notifications/triggers/referral-verified/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notifications/triggers/referral-verified">> = Specific
  const handler = {} as typeof import("../../src/app/api/notifications/triggers/referral-verified/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/notifications/triggers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notifications/triggers">> = Specific
  const handler = {} as typeof import("../../src/app/api/notifications/triggers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/payments/create/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payments/create">> = Specific
  const handler = {} as typeof import("../../src/app/api/payments/create/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/payments/upload-receipt/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payments/upload-receipt">> = Specific
  const handler = {} as typeof import("../../src/app/api/payments/upload-receipt/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ping/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ping">> = Specific
  const handler = {} as typeof import("../../src/app/api/ping/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/process-expense/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/process-expense">> = Specific
  const handler = {} as typeof import("../../src/app/api/process-expense/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/referrals/activate-smart/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/referrals/activate-smart">> = Specific
  const handler = {} as typeof import("../../src/app/api/referrals/activate-smart/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/referrals/validate-code/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/referrals/validate-code">> = Specific
  const handler = {} as typeof import("../../src/app/api/referrals/validate-code/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/test/smart-activation/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/test/smart-activation">> = Specific
  const handler = {} as typeof import("../../src/app/api/test/smart-activation/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/webhooks/baileys/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webhooks/baileys">> = Specific
  const handler = {} as typeof import("../../src/app/api/webhooks/baileys/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/webhooks/whatsapp/confirm/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webhooks/whatsapp/confirm">> = Specific
  const handler = {} as typeof import("../../src/app/api/webhooks/whatsapp/confirm/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/webhooks/whatsapp/debug/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webhooks/whatsapp/debug">> = Specific
  const handler = {} as typeof import("../../src/app/api/webhooks/whatsapp/debug/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/webhooks/whatsapp/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webhooks/whatsapp">> = Specific
  const handler = {} as typeof import("../../src/app/api/webhooks/whatsapp/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/whatsapp/events/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/whatsapp/events">> = Specific
  const handler = {} as typeof import("../../src/app/api/whatsapp/events/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/whatsapp/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/whatsapp/health">> = Specific
  const handler = {} as typeof import("../../src/app/api/whatsapp/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/whatsapp/metrics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/whatsapp/metrics">> = Specific
  const handler = {} as typeof import("../../src/app/api/whatsapp/metrics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/whatsapp/send-verification-code/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/whatsapp/send-verification-code">> = Specific
  const handler = {} as typeof import("../../src/app/api/whatsapp/send-verification-code/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/whatsapp/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/whatsapp/status">> = Specific
  const handler = {} as typeof import("../../src/app/api/whatsapp/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/whatsapp/test-token/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/whatsapp/test-token">> = Specific
  const handler = {} as typeof import("../../src/app/api/whatsapp/test-token/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/whatsapp/verify-code/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/whatsapp/verify-code">> = Specific
  const handler = {} as typeof import("../../src/app/api/whatsapp/verify-code/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
