version: '3.8'

services:
  baileys-worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ahorro365-baileys-worker
    restart: always
    ports:
      - "3003:3003"
    volumes:
      - ./auth_info:/app/auth_info
      - ./logs:/app/logs
    environment:
      - NODE_ENV=production
      - PORT=3003
      - BAILEYS_SESSION_PATH=/app/auth_info
    env_file:
      - .env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

