app = "ahorro365-baileys-worker"
primary_region = "dfw"

[build]

[http_service]
  internal_port = 3003
  force_https = true
  
  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    timeout = "5s"
    method = "GET"
    path = "/health"

[[mounts]]
  source = "auth_info"
  destination = "/app/auth_info"

[vm]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
