app = "ahorro365-baileys-worker"
primary_region = "dfw"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "3003"
  BAILEYS_SESSION_PATH = "/app/auth_info"

[http_service]
  internal_port = 3003
  force_https = true
  auto_stop_machines = "off"
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[mounts]]
  source = "auth_info"
  destination = "/app/auth_info"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256